### ISSUE TITLE
[Config] 프로젝트 기본 세팅

### ISSUE THREAD

**Issue by jane1choi** [dnd-side-project/dnd-10th-10-iOS#1]
## 🚀 Feature Issue
- 프로젝트 기본 세팅을 진행합니다.

## 📝 To-do
- [x] 프로젝트 파일 생성
- [x] 폴더 구조 구성
- [x] SPM 설치
- [x] Apple Login 및 ScreenTime API 사용을 위한 인증서 세팅
