### ISSUE TITLE
[Feat] UI 홈 탭 메인 화면 구현

### ISSUE THREAD

**Issue by sunny5875** [dnd-side-project/dnd-10th-10-iOS#18]
## 🚀 Feature Issue
-  홈 탭에 있는 메인 화면을 구성합니댜

## 📝 To-do
- [x] task 작성
- [x] 참여방, 종료방 탭바 추가
- [x] 방이 없을 때의 UI
- [x] 방이 있을 때의 UI
