### ISSUE TITLE
[Config] 네트워크 레이어 세팅

### ISSUE THREAD

**Issue by jane1choi** [dnd-side-project/dnd-10th-10-iOS#25]
## 🚀 Feature Issue
- Moya + Combine 을 이용한 네트워크 레이어 세팅을 진행합니다.

## 📝 To-do
- [ ] 서버 response 확인 후 GenericResponse 구조 짜기
- [ ] 모든 통신에 공통적으로 필요한 파일 세팅
- [ ] Combine을 이용한 비동기처리 가능하도록 return 타입 세팅
