### ISSUE TITLE
[Feat] 방 디테일 domain 구현

### ISSUE THREAD

**Issue by sunny5875** [dnd-side-project/dnd-10th-10-iOS#40]
## 🚀 Feature Issue
- 방 디테일 화면에 대한 domain을 구현

## 📝 To-do
- [ ] task 작성
- [ ] 방 조회 api 연결
- [ ] 방 랭킹 api 연결
- [ ] 진행상황 api 연결
