### ISSUE TITLE
[Feat] 공통 네비게이션 바 UI 구성

### ISSUE THREAD

**Issue by jane1choi** [dnd-side-project/dnd-10th-10-iOS#6]
## 🚀 Feature Issue
- 앱 전역에서 공통적으로 사용되는 네비게이션 바 UI를 구성합니다.

## 📝 To-do
- [x] 뒤로가기 버튼만 있는 네비바
- [x] 뒤로가기 버튼 + 중앙 타이틀
- [x] 로고 이미지 + 오른쪽 버튼
- [x] 왼쪽 타이틀 + 오른쪽 버튼(2개 까지)
